'use client';
import { useState } from 'react';
import { useApp } from '@/context/language-context';
import type { InvoiceEntity } from '@/types/invoice';
import { clearanceIssues, hasZatcaCode, needsSourceRefresh, makeReviewPack, csvDocument } from '@/lib/services/clearance-workspace';
import { downloadDocument } from '@/lib/utils/download-document';
import { ClipboardCheck, Download } from 'lucide-react';

export function ClearanceReadiness({invoice,onReview}:{invoice:InvoiceEntity;onReview:(line:number)=>void}) {
  const {language,role}=useApp();const text=(en:string,ar:string)=>language==='ar'?ar:en;
  const [filter,setFilter]=useState('all');
  const rows=invoice.lineItems.map(item=>({item,issues:clearanceIssues(item)}));
  const pending=rows.filter(row=>row.issues.length);
  const visible=pending.filter(({item})=>filter==='all'||filter==='code'&&!hasZatcaCode(item)||filter==='refresh'&&needsSourceRefresh(item)||filter==='blocked'&&['PROHIBITED','RESTRICTED'].includes(item.regulatoryStatus));
  const requirements=[...new Set(invoice.lineItems.flatMap(item=>item.classificationEvidence?.certificateRequirements?[item.classificationEvidence.certificateRequirements]:[]))];
  const exportIssues=()=>downloadDocument(`review-actions-${invoice.invoiceNumber}.csv`,csvDocument([['Line','Product','HS code','Actions','Missing product details','Source checked at'],...pending.map(({item,issues})=>[item.lineNumber,item.description,item.matchedHsCode,issues.join('; '),item.classificationEvidence?.missingDetails?.join('; '),item.classificationEvidence?.checkedAt])]),'text/csv;charset=utf-8');
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-lg font-bold"><ClipboardCheck className="h-5 w-5 text-emerald-700" />{text('Clearance preparation','التحضير للتخليص')}</h2><p className="mt-2 text-xs text-slate-500">{pending.length} / {rows.length} {text('items need action before classification review is complete.','بند يحتاج إلى إجراء لإكمال مراجعة التصنيف.')}</p></div><div className="flex flex-wrap gap-2"><button className="rounded-lg border px-3 py-2 text-xs disabled:opacity-40 dark:border-slate-700" disabled={!pending.length} onClick={exportIssues}>{text('Export action list','تصدير الإجراءات')}</button><button className="flex items-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-xs text-white" onClick={()=>downloadDocument(`clearance-review-${invoice.invoiceNumber}.json`,JSON.stringify(makeReviewPack(invoice),null,2),'application/json')}><Download className="h-4 w-4" />{text('Download review pack','تنزيل ملف المراجعة')}</button></div></div>
    <div className="my-4 flex flex-wrap gap-2">{[{value:'all',label:text('All actions','كل الإجراءات')},{value:'code',label:text('Missing HS codes','رموز غير محددة')},{value:'blocked',label:text('Import restrictions','قيود الاستيراد')},{value:'refresh',label:text('Source rechecks','تحديث المصادر')}].map(option=><button key={option.value} aria-pressed={filter===option.value} onClick={()=>setFilter(option.value)} className={`rounded-full border px-3 py-1.5 text-xs ${filter===option.value?'border-emerald-600 bg-emerald-50 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200':'border-slate-200 dark:border-slate-700'}`}>{option.label}</button>)}</div>
    <div className="max-h-80 overflow-auto rounded-xl border dark:border-slate-700">
      {!visible.length ? <p className="p-5 text-sm text-slate-500">{text('No pending items in this filter.','لا توجد بنود معلقة ضمن هذا المرشح.')}</p> : visible.map(({item,issues})=><div key={item.id} className="flex flex-wrap items-start gap-3 border-b p-4 last:border-0 dark:border-slate-800"><span className="rounded bg-slate-100 px-2 py-1 text-xs font-bold dark:bg-slate-800">{item.lineNumber}</span><div className="min-w-0 flex-1"><p className="break-words text-xs font-semibold">{item.description}</p><p className="mt-1 text-xs leading-relaxed text-amber-700 dark:text-amber-300">{issues.join(' · ')}</p>{item.classificationEvidence?.missingDetails?.map(detail=><p key={detail} className="mt-1 text-xs text-slate-500">{detail}</p>)}</div>{role!=='AUDITOR'&&<button className="rounded-lg border px-3 py-2 text-xs font-semibold text-emerald-700 dark:border-slate-700 dark:text-emerald-400" onClick={()=>onReview(item.lineNumber)}>{text('Review item','مراجعة البند')}</button>}</div>)}
    </div>
    <details className="mt-4 text-xs"><summary className="cursor-pointer font-semibold">{text('Document requirements to prepare','متطلبات المستندات للتحضير')} ({requirements.length})</summary><p className="mt-2 text-slate-500">{text('Requirement text comes from ZATCA records. Document possession, validity and acceptance have not been verified.','نص المتطلبات من سجلات الهيئة. لم يتم التحقق من توفر المستندات أو صلاحيتها أو قبولها.')}</p>{requirements.map(requirement=><p className="mt-3 rounded-lg bg-slate-50 p-3 leading-relaxed dark:bg-slate-800" dir="auto" key={requirement}>{requirement}</p>)}</details>
    <p className="mt-4 text-xs leading-relaxed text-slate-500">{text('This checklist supports preparation. Customs valuation, exemptions and document acceptance still require assessment. FASAH submission is not connected. Source rechecks after 30 days are an internal reminder.','تدعم هذه القائمة التحضير. يبقى تقييم القيمة والإعفاءات وقبول المستندات مطلوباً. إرسال فسح غير متصل. تحديث المصدر بعد 30 يوماً تذكير داخلي.')}</p>
  </section>;
}
