'use client';
import { useMemo, useState } from 'react';
import type { InvoiceEntity } from '@/types/invoice';
import { collectHsCodes, csvDocument, SOURCE_RECHECK_DAYS } from '@/lib/services/clearance-workspace';
import { downloadDocument } from '@/lib/utils/download-document';
import { useApp } from '@/context/language-context';
import { BookOpen, Download, Search, ArrowUpRight } from 'lucide-react';

export function HsCodeLibrary({invoices,onLookup,onOpenInvoice}:{invoices:InvoiceEntity[];onLookup:(code?:string)=>void;onOpenInvoice:(id:string)=>void}) {
  const {language}=useApp();const ar=language==='ar';const text=(en:string,arabic:string)=>ar?arabic:en;
  const [query,setQuery]=useState('');const [filter,setFilter]=useState('all');const [limit,setLimit]=useState(20);
  const codes=useMemo(()=>collectHsCodes(invoices),[invoices]);
  const filtered=codes.filter(code=>{
    const q=query.trim().toLowerCase();
    return (!q || [code.hsCode,code.latest.classificationEvidence?.tariffDescription,...code.products.flatMap(p=>[p.description,p.origin,p.invoiceNumber])].join(' ').toLowerCase().includes(q)) &&
      (filter==='all' || (filter==='reviewed' && code.reviewedCount>0) || (filter==='refresh' && code.refreshNeeded) || code.latest.regulatoryStatus===filter);
  });
  const exportCsv=()=>downloadDocument('collected-hs-codes.csv',csvDocument([
    ['HS code','ZATCA description','Last recorded duty %','ZATCA customs controls','Requirements','Source checked at','Recheck reminder','Reviewed products','Products observed','Invoice products','Source URL'],
    ...filtered.map(code=>[code.hsCode,code.latest.classificationEvidence?.tariffDescription,code.latest.dutyRate,code.latest.regulatoryStatus,code.latest.classificationEvidence?.certificateRequirements,code.checkedAt,code.refreshNeeded?'Recheck needed':'Within reminder window',code.reviewedCount,code.products.length,code.products.map(p=>`${p.invoiceNumber} / ${p.lineNumber}: ${p.description}`).join('\n'),code.latest.classificationEvidence?.zatcaUrl]),
  ]),'text/csv;charset=utf-8');
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6 dark:border-slate-800 dark:bg-slate-900">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-emerald-700 dark:text-emerald-400">{text('YOUR CLASSIFICATION KNOWLEDGE','معرفتك بالتصنيف')}</p><h2 className="mt-2 text-2xl font-bold">{text('HS code library','مكتبة الرموز الجمركية')}</h2><p className="mt-2 max-w-2xl text-xs leading-relaxed text-slate-500">{text('Automatically collected from saved ZATCA-backed invoice results. Repeated uploads are deduplicated; source values are historical snapshots, not guaranteed current rates.','تُجمع تلقائياً من نتائج الفواتير المحفوظة المستندة إلى الهيئة، مع إزالة تكرار الرفع. القيم المحفوظة تاريخية وليست ضماناً للمعدلات الحالية.')}</p></div><div className="flex flex-wrap gap-2"><button className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs disabled:opacity-40" disabled={!filtered.length} onClick={exportCsv}><Download className="h-4 w-4" />{text('Export collection','تصدير المجموعة')}</button><button className="flex items-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-xs text-white" onClick={()=>onLookup()}><Search className="h-4 w-4" />{text('Live ZATCA search','بحث مباشر في الهيئة')}</button><a href="https://eservices.zatca.gov.sa/sites/sc/en/tariff/Pages/TariffPages/TariffSearch.aspx" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"><ArrowUpRight className="h-4 w-4" />{text('Official ZATCA portal', 'البوابة الرسمية للهيئة')}</a><a href="https://saber.sa/home/hscodesearch" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 rounded-lg border px-3 py-2 text-xs hover:bg-slate-50 dark:border-slate-700 dark:hover:bg-slate-800"><ArrowUpRight className="h-4 w-4" />{text('Saber portal', 'بوابة سابر')}</a></div></div>
    <div className="my-5 grid grid-cols-3 gap-3">{[[codes.length,text('unique codes','رمز فريد')],[codes.filter(x=>x.reviewedCount>0).length,text('with reviewed products','مع منتجات مراجعة')],[codes.filter(x=>x.refreshNeeded).length,text('need source recheck','تحتاج إعادة التحقق')]].map(([value,label])=><div key={label} className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><strong className="block text-2xl tabular-nums">{value}</strong><span className="text-xs text-slate-500 dark:text-slate-400">{label}</span></div>)}</div>
    <div className="mb-4 flex flex-col gap-3 sm:flex-row"><input value={query} onChange={e=>{setQuery(e.target.value);setLimit(20);}} aria-label={text('Search collected codes','بحث الرموز المجمعة')} placeholder={text('HS code, product, invoice or origin…','رمز جمركي أو منتج أو فاتورة أو منشأ…')} className="min-w-0 flex-1 rounded-lg border bg-transparent p-3 text-sm dark:border-slate-700" /><select value={filter} onChange={e=>{setFilter(e.target.value);setLimit(20);}} aria-label={text('Collection filter','تصفية المكتبة')} className="rounded-lg border bg-white p-3 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="all">{text('All codes','كل الرموز')}</option><option value="reviewed">{text('Has reviewed products','تتضمن منتجات مراجعة')}</option><option value="refresh">{text('Recheck needed','إعادة التحقق مطلوبة')}</option><option value="REGULATED">{text('Regulated','خاضع للمتطلبات')}</option><option value="NON_REGULATED">{text('Non-regulated','غير خاضع')}</option><option value="PROHIBITED">{text('Prohibited','ممنوع')}</option><option value="RESTRICTED">{text('Restricted','مقيد')}</option></select></div>
    <p className="mb-4 text-xs text-slate-500">{filtered.length} {text('codes · Source reminders use a','رمز · التذكير بالمصدر بعد')} {SOURCE_RECHECK_DAYS}{text('-day workspace interval, not a legal validity period.',' يوماً كإجراء داخلي وليس مدة صلاحية قانونية.')}</p>
    {!filtered.length && <div className="rounded-xl border border-dashed p-10 text-center text-sm text-slate-500"><BookOpen className="mx-auto mb-3 h-7 w-7" />{codes.length ? text('No codes match these filters.','لا توجد نتائج مطابقة.') : text('Upload and classify an invoice to start your collection.','ارفع وصنّف فاتورة لبدء مجموعتك.')}</div>}
    <div className="grid gap-4 2xl:grid-cols-2">{filtered.slice(0,limit).map(code=><article key={code.hsCode} className="min-w-0 rounded-xl border border-slate-200 p-4 dark:border-slate-700">
      <div className="flex flex-wrap items-center justify-between gap-2"><h3 dir="ltr" className="font-mono text-lg font-bold text-emerald-700 dark:text-emerald-400">{code.hsCode}</h3><button className="flex items-center gap-1 text-xs font-semibold text-emerald-700 dark:text-emerald-400" onClick={()=>onLookup(code.hsCode)}>{text('Recheck in ZATCA','إعادة التحقق لدى الهيئة')}<ArrowUpRight className="h-4 w-4" /></button></div>
      <p className="my-3 text-sm leading-relaxed">{code.latest.classificationEvidence?.tariffDescription}</p><div className="flex flex-wrap gap-2 text-xs"><span className="rounded bg-slate-100 px-2 py-1 dark:bg-slate-800">{text('Recorded duty','الرسوم المسجلة')}: {code.latest.dutyRate===null?'—':code.latest.dutyRate+'%'}</span><span className="rounded bg-slate-100 px-2 py-1 dark:bg-slate-800">{code.latest.regulatoryStatus.replaceAll('_',' ')}</span><span className="rounded bg-slate-100 px-2 py-1 dark:bg-slate-800">{code.reviewedCount} / {code.products.length} {text('reviewed','مراجعة')}</span></div>
      <p className="mt-3 text-xs text-slate-500">{text('Source checked','آخر تحقق')}: {code.checkedAt && Number.isFinite(Date.parse(code.checkedAt)) ? new Date(code.checkedAt).toLocaleString(ar?'ar-SA':'en-GB'):'—'}</p>{code.refreshNeeded && <p className="mt-2 text-xs text-amber-700 dark:text-amber-300">{text('Recheck this source before reuse.','أعد التحقق من المصدر قبل الاستخدام.')}</p>}{code.ratesObserved.length>1 && <p className="mt-2 text-xs text-amber-700 dark:text-amber-300">{text('Different rates appear in saved observations. Verify the current tariff.','توجد معدلات مختلفة في السجلات المحفوظة. تحقق من التعرفة الحالية.')}</p>}
      <details className="mt-3 border-t pt-3 text-xs dark:border-slate-700"><summary className="cursor-pointer font-semibold">{text('Product history & requirements','سجل المنتجات والمتطلبات')}</summary><p className="my-3 leading-relaxed" dir="auto">{code.latest.classificationEvidence?.certificateRequirements || text('No requirement text recorded; consult the source.','لا يوجد نص متطلبات محفوظ؛ راجع المصدر.')}</p>{code.products.map(p=><div key={p.invoiceId+':'+p.lineNumber} className="border-t py-3 dark:border-slate-800"><p className="leading-relaxed">{p.description}</p><button className="mt-1 text-emerald-700 underline dark:text-emerald-400" onClick={()=>onOpenInvoice(p.invoiceId)}>{p.invoiceNumber} · {text('Line','بند')} {p.lineNumber}</button></div>)}</details>
    </article>)}</div>
    {filtered.length>limit && <button className="mt-5 w-full rounded-lg border p-3 text-sm dark:border-slate-700" onClick={()=>setLimit(n=>n+20)}>{text('Show more codes','عرض المزيد')}</button>}
  </section>;
}
